<?php

namespace Database\Seeders;

use App\Models\CountryGuide;
use Illuminate\Database\Seeder;

class CountryGuidesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'country' => 'Sénégal',
                'country_code' => 'SN',
                'flag' => '🇸🇳',
                'currency' => 'XOF',
                'official_language' => 'Français',
                'population' => 18,
                'gdp' => 27.6,
                'gdp_growth' => 4.7,
                'remittances_gdp' => 10.7,
                'ease_of_business_score' => 52.4,
                'key_sectors' => ['Agritech', 'Fintech', 'Énergie', 'Tourisme & Culture'],
                'legal_framework' => "Le Sénégal dispose d'un cadre juridique favorable à l'investissement étranger via l'OHADA (Organisation pour l'Harmonisation en Afrique du Droit des Affaires). La création d'entreprise est simplifiée grâce au guichet unique de l'APIX. Les investisseurs étrangers bénéficient des mêmes droits que les nationaux.\n\n**Formes juridiques courantes :**\n- SARL (Société à Responsabilité Limitée)\n- SA (Société Anonyme)\n- SAS (Société par Actions Simplifiée)\n- Succursale d'entreprise étrangère\n\n**Délai de création :** 2-5 jours via l'APIX.",
                'taxation' => "**Impôt sur les sociétés :** 30%\n**TVA :** 18%\n**Impôt sur les dividendes :** 10% (retenue à la source)\n**Conventions fiscales :** accords de non-double imposition avec la France, le Canada, la Belgique, et d'autres pays.\n\n**Zones économiques spéciales :** taux réduit de 15% pour les entreprises en ZES (Diamniadio, Diass).",
                'investment_incentives' => "- **Code des investissements (2004 révisé 2012)** : exonérations fiscales de 5 à 12 ans selon la zone\n- **Startup Act (2019)** : label startup avec avantages fiscaux (exonération IS 3 ans, TVA réduite)\n- **Zone Économique Spéciale de Diamniadio** : infrastructure, avantages fiscaux, guichet unique\n- **PSE (Plan Sénégal Émergent)** : cadre stratégique national avec priorités sectorielles claires",
                'risks' => "- Lourdeurs administratives malgré les réformes\n- Accès au foncier parfois complexe\n- Instabilité énergétique dans certaines régions\n- Marché intérieur de taille moyenne (18M habitants)\n- Concurrence régionale (Côte d'Ivoire, Ghana)",
                'opportunities' => "- Hub numérique d'Afrique de l'Ouest (Dakar)\n- Découverte de gaz et pétrole (GTA, Sangomar) dès 2024\n- Population jeune et connectée (70% < 35 ans)\n- Stabilité politique historique\n- Position géographique stratégique (proximité Europe/Amériques)\n- Écosystème startup dynamique",
                'diaspora_programs' => "- **FAISE (Fonds d'Appui à l'Investissement des Sénégalais de l'Extérieur)** : fonds gouvernemental de financement\n- **PAISD (Programme d'Appui aux Initiatives de Solidarité pour le Développement)** : accompagnement technique\n- **BAOS (Bureau d'Accueil, d'Orientation et de Suivi)** : guichet dédié dans les consulats\n- **Convention fiscale France-Sénégal** : éviter la double imposition",
                'investment_agency' => 'APIX (Agence de Promotion des Investissements et Grands Travaux)',
                'investment_agency_url' => 'https://investinsenegal.com',
            ],
            [
                'country' => 'Côte d\'Ivoire',
                'country_code' => 'CI',
                'flag' => '🇨🇮',
                'currency' => 'XOF',
                'official_language' => 'Français',
                'population' => 28,
                'gdp' => 70.0,
                'gdp_growth' => 6.5,
                'remittances_gdp' => 1.3,
                'ease_of_business_score' => 60.7,
                'key_sectors' => ['Agritech', 'Fintech', 'Énergie', 'Industrie'],
                'legal_framework' => "La Côte d'Ivoire est membre de l'OHADA et de l'UEMOA. Le Centre de Promotion des Investissements (CEPICI) offre un guichet unique pour la création d'entreprise en 24h. Le pays a engagé d'importantes réformes pour améliorer le climat des affaires.\n\n**Formes juridiques :** SARL, SA, SAS, GIE\n**Délai de création :** 24-72h via le CEPICI.",
                'taxation' => "**IS :** 25%\n**TVA :** 18%\n**Retenue sur dividendes :** 15%\n**BIC (régime simplifié) :** 2% du CA pour les micro-entreprises\n\n**Zone franche de Grand-Bassam et VITIB (Biotechnologie) :** exonération totale pendant 5 ans.",
                'investment_incentives' => "- **Code des Investissements (2012, révisé 2018)** : agréments avec exonérations de 5 à 15 ans\n- **PND 2021-2025** : programme national avec investissements massifs en infrastructure\n- **Zones industrielles** : Yopougon, PK24, Grand-Bassam\n- **PPP (Partenariat Public-Privé)** : cadre juridique solide",
                'risks' => "- Risque politique résiduel (crises 2010-2011, 2020)\n- Corruption malgré les progrès\n- Dépendance au cacao (1er producteur mondial)\n- Disparités régionales (Abidjan vs intérieur)",
                'opportunities' => "- 1ère économie de l'UEMOA\n- Croissance parmi les plus fortes d'Afrique (+6.5%)\n- Hub logistique (Port d'Abidjan, Aéroport Félix Houphouët-Boigny)\n- Classe moyenne urbaine en expansion\n- Transformation agricole (cacao, cajou, hévéa)",
                'diaspora_programs' => "- **ODCI (Office de la Diaspora de Côte d'Ivoire)** : accompagnement au retour et à l'investissement\n- **Fonds de Garantie pour les Ivoiriens de la Diaspora**\n- **Salon CIEID** : Conférence Internationale Économique des Ivoiriens de la Diaspora",
                'investment_agency' => 'CEPICI (Centre de Promotion des Investissements en Côte d\'Ivoire)',
                'investment_agency_url' => 'https://www.cepici.gouv.ci',
            ],
            [
                'country' => 'Nigeria',
                'country_code' => 'NG',
                'flag' => '🇳🇬',
                'currency' => 'NGN',
                'official_language' => 'English',
                'population' => 223,
                'gdp' => 477.0,
                'gdp_growth' => 3.3,
                'remittances_gdp' => 4.2,
                'ease_of_business_score' => 56.9,
                'key_sectors' => ['Fintech', 'Énergie', 'Agritech', 'Commerce & Retail'],
                'legal_framework' => "Le Nigeria opère sous un système juridique mixte (common law + droit coutumier). La Corporate Affairs Commission (CAC) gère l'immatriculation des entreprises. Les réformes récentes permettent l'enregistrement en ligne en 24-48h.\n\n**Formes juridiques :** Limited Liability Company (LLC), Public Limited Company (PLC), Business Name\n**Délai :** 24-48h en ligne.",
                'taxation' => "**Company Income Tax :** 30% (réduction à 20% pour les PME < ₦25M CA)\n**VAT :** 7.5%\n**Withholding Tax sur dividendes :** 10%\n**Pioneer Status :** exonération IS de 3 à 5 ans pour les secteurs prioritaires.",
                'investment_incentives' => "- **NIPC (Nigerian Investment Promotion Commission)** : guichet unique\n- **Pioneer Status Incentive** : exonération IS 3-5 ans\n- **Free Trade Zones** : Lekki, Calabar, Kano\n- **Startup Act (2022)** : Labelling + incentives pour les startups tech",
                'risks' => "- Instabilité sécuritaire (nord, delta du Niger)\n- Volatilité du naira\n- Infrastructure défaillante (énergie, routes)\n- Complexité réglementaire multi-niveaux (fédéral, états, local)\n- Rapatriement des capitaux parfois difficile",
                'opportunities' => "- Plus grande économie d'Afrique (PIB $477Md)\n- 1er marché consommateur (223M habitants)\n- Écosystème tech le plus mature du continent (Lagos)\n- Production pétrolière + transition énergétique\n- Marché de consommation en forte croissance",
                'diaspora_programs' => "- **Nigerians in Diaspora Commission (NiDCOM)** : institution fédérale dédiée\n- **Diaspora Bonds** : obligations souveraines ciblées diaspora\n- **Diaspora Mortgage Window** : accès au crédit immobilier depuis l'étranger\n- **NiDCOM Investment Summit** annuel",
                'investment_agency' => 'NIPC (Nigerian Investment Promotion Commission)',
                'investment_agency_url' => 'https://www.nipc.gov.ng',
            ],
            [
                'country' => 'Maroc',
                'country_code' => 'MA',
                'flag' => '🇲🇦',
                'currency' => 'MAD',
                'official_language' => 'Arabe / Français',
                'population' => 37,
                'gdp' => 134.0,
                'gdp_growth' => 3.0,
                'remittances_gdp' => 7.4,
                'ease_of_business_score' => 73.4,
                'key_sectors' => ['Industrie', 'Fintech', 'Énergie', 'Tourisme & Culture'],
                'legal_framework' => "Le Maroc dispose d'un cadre juridique moderne et d'un système judiciaire commercial dédié. Les tribunaux de commerce traitent les litiges d'affaires. La Charte de l'Investissement (2022) a renforcé les protections des investisseurs.\n\n**Formes juridiques :** SARL, SA, SAS, Succursale\n**Délai de création :** 24-48h via le CRI (Centre Régional d'Investissement).",
                'taxation' => "**IS :** 20% (PME) à 35% (grandes entreprises, financières)\n**TVA :** 20%\n**Retenue dividendes :** 15%\n**Zones Franches d'Exportation :** IS 0% les 5 premières années, puis 20%.\n**Casablanca Finance City :** IS 15% plafonné.",
                'investment_incentives' => "- **Charte de l'Investissement 2022** : subventions jusqu'à 30% du montant investi\n- **Casablanca Finance City** : hub financier avec statut fiscal avantageux\n- **Zones Franches** : Tanger Med, Kénitra, Fès\n- **Fonds Mohammed VI** pour l'investissement\n- **Plan Génération Green** (agriculture) et **Plan de relance industrielle**",
                'risks' => "- Stress hydrique important\n- Disparités régionales marquées\n- Chômage des jeunes élevé\n- Dépendance aux importations énergétiques (en baisse avec le solaire)",
                'opportunities' => "- Stabilité politique et institutionnelle\n- Infrastructure de classe mondiale (Tanger Med, TGV, autoroutes)\n- Plateforme industrielle vers l'Europe et l'Afrique\n- Leader continental en énergies renouvelables (Noor Ouarzazate)\n- Positionnement comme hub financier africain (CFC)",
                'diaspora_programs' => "- **MDM (Marocains Du Monde)** : portail officiel\n- **Fondation Hassan II pour les MRE** : accompagnement\n- **Invest in Morocco Roadshows** dans les pays de résidence\n- **Conventions fiscales** avec +60 pays\n- **Transferts via banques marocaines** à l'étranger (Attijariwafa, BMCE)",
                'investment_agency' => 'AMDIE (Agence Marocaine de Développement des Investissements et des Exportations)',
                'investment_agency_url' => 'https://www.investangier.com',
            ],
            [
                'country' => 'Kenya',
                'country_code' => 'KE',
                'flag' => '🇰🇪',
                'currency' => 'KES',
                'official_language' => 'English / Kiswahili',
                'population' => 54,
                'gdp' => 110.0,
                'gdp_growth' => 5.0,
                'remittances_gdp' => 3.4,
                'ease_of_business_score' => 73.2,
                'key_sectors' => ['Fintech', 'Agritech', 'Énergie', 'Healthtech'],
                'legal_framework' => "Le Kenya fonctionne sous un système de common law. Le Business Registration Service (BRS) permet l'enregistrement en ligne. La Kenya Investment Authority (KenInvest) accompagne les investisseurs étrangers.\n\n**Formes :** Private Limited Company, LLP, Branch Office\n**Délai :** 3-7 jours.",
                'taxation' => "**Corporation Tax :** 30% (résidents), 37.5% (non-résidents)\n**VAT :** 16%\n**Withholding Tax dividendes :** 15% (non-résidents)\n**Special Economic Zones :** 10% IS pour 10 ans, puis 15%.",
                'investment_incentives' => "- **Kenya Vision 2030** : cadre stratégique\n- **Special Economic Zones** : 4 zones actives\n- **Konza Technopolis** : silicon savannah en développement\n- **Export Processing Zones** : exonération IS 10 ans\n- **Startup Bill (2022)** : cadre pour les startups tech",
                'risks' => "- Instabilité politique périodique (élections)\n- Corruption persistante\n- Coût de la vie élevé (Nairobi)\n- Dette publique croissante",
                'opportunities' => "- Hub tech #1 d'Afrique de l'Est (Silicon Savannah)\n- M-Pesa : leader mondial mobile money\n- Population éduquée et anglophone\n- Port de Mombasa : porte d'entrée de l'Afrique de l'Est\n- Écosystème startup mature (iHub, Nairobi Garage)",
                'diaspora_programs' => "- **Kenya Diaspora Policy** : cadre national\n- **Diaspora Affairs Office** (Ministry of Foreign Affairs)\n- **Kenya Diaspora Bond** (infrastructure)\n- **Exemptions** sur les véhicules et équipements importés pour projets d'investissement",
                'investment_agency' => 'KenInvest (Kenya Investment Authority)',
                'investment_agency_url' => 'https://www.invest.go.ke',
            ],
            [
                'country' => 'Rwanda',
                'country_code' => 'RW',
                'flag' => '🇷🇼',
                'currency' => 'RWF',
                'official_language' => 'Kinyarwanda / English / French',
                'population' => 14,
                'gdp' => 11.1,
                'gdp_growth' => 7.0,
                'remittances_gdp' => 2.8,
                'ease_of_business_score' => 76.5,
                'key_sectors' => ['Fintech', 'Healthtech', 'Edtech', 'Tourisme & Culture'],
                'legal_framework' => "Le Rwanda est reconnu pour sa gouvernance exemplaire en Afrique. La création d'entreprise se fait en 4h via le Rwanda Development Board (RDB). Tolérance zéro pour la corruption.\n\n**Formes :** Ltd, PLC, Branch, Joint Venture\n**Délai :** 4-6 heures (!)",
                'taxation' => "**IS :** 30% (standard), 0% pour les investisseurs stratégiques enregistrés\n**TVA :** 18%\n**Retenue dividendes :** 15% (5% avec convention)\n**ICT & innovation :** taux préférentiel de 0-15%.",
                'investment_incentives' => "- **Création d'entreprise en 6h** (record africain)\n- **Kigali International Financial Centre** : hub financier\n- **Kigali Innovation City** : campus tech + éducation\n- **7 ans d'exonération** pour investissements > $50M\n- **Free Trade Zone** régime\n- **Smart Rwanda Master Plan** : transformation digitale nationale",
                'risks' => "- Marché intérieur restreint (14M habitants)\n- Enclavement (pas d'accès à la mer)\n- Dépendance aux aides internationales\n- Liberté de presse limitée",
                'opportunities' => "- Meilleur climat des affaires d'Afrique subsaharienne\n- Ambition de devenir le \"Singapour de l'Afrique\"\n- Propreté et sécurité exceptionnelles\n- Hub de conférences (Kigali Convention Centre)\n- Drone delivery (Zipline) : innovation technologique",
                'diaspora_programs' => "- **Rwanda Diaspora Global Network**\n- **Diaspora Mutual Fund** (RDGN)\n- **Annual Diaspora Conference** à Kigali\n- **e-Residency** en développement\n- **RDB Diaspora Desk** : accompagnement personnalisé",
                'investment_agency' => 'RDB (Rwanda Development Board)',
                'investment_agency_url' => 'https://rdb.rw',
            ],
            [
                'country' => 'Cameroun',
                'country_code' => 'CM',
                'flag' => '🇨🇲',
                'currency' => 'XAF',
                'official_language' => 'Français / English',
                'population' => 28,
                'gdp' => 44.3,
                'gdp_growth' => 3.8,
                'remittances_gdp' => 0.9,
                'ease_of_business_score' => 46.1,
                'key_sectors' => ['Agritech', 'Énergie', 'Industrie', 'Commerce & Retail'],
                'legal_framework' => "Le Cameroun est membre de l'OHADA et de la CEMAC. Le Centre de Formalités de Création d'Entreprise (CFCE) est le guichet unique.\n\n**Formes :** SARL, SA, SNC, Établissement\n**Délai :** 3-7 jours.",
                'taxation' => "**IS :** 33% (+ 10% de centimes additionnels = 36.3% effectif)\n**TVA :** 19.25%\n**Retenue dividendes :** 16.5%\n**Régime simplifié** pour les PME.",
                'investment_incentives' => "- **Charte des investissements (2013)** : exonérations sectorielles\n- **Zone franche industrielle de Kribi** (port en eau profonde)\n- **Loi sur les startups (2024)** en cours de mise en œuvre\n- **CEMAC** : marché commun de 55M d'habitants",
                'risks' => "- Instabilité sécuritaire (régions anglophones, Extrême-Nord)\n- Lourdeurs bureaucratiques\n- Corruption élevée\n- Infrastructure insuffisante",
                'opportunities' => "- 2ème économie de la CEMAC\n- Bilinguisme (français/anglais) : passerelle\n- Ressources naturelles abondantes (pétrole, bois, minerais)\n- Port en eau profonde de Kribi\n- Forte demande en transformation agroalimentaire",
                'diaspora_programs' => "- **Ministère des Relations Extérieures — Sous-direction Diaspora**\n- **Compte d'Affectation Spéciale de la Diaspora** (en discussion)\n- **Salon des Camerounais de la Diaspora** annuel",
                'investment_agency' => 'API (Agence de Promotion des Investissements)',
                'investment_agency_url' => 'https://www.api.cm',
            ],
            [
                'country' => 'Ghana',
                'country_code' => 'GH',
                'flag' => '🇬🇭',
                'currency' => 'GHS',
                'official_language' => 'English',
                'population' => 33,
                'gdp' => 73.0,
                'gdp_growth' => 3.2,
                'remittances_gdp' => 5.6,
                'ease_of_business_score' => 60.0,
                'key_sectors' => ['Fintech', 'Agritech', 'Énergie', 'Edtech'],
                'legal_framework' => "Le Ghana opère sous un système de common law. Le Registrar General's Department gère l'immatriculation. GIPC (Ghana Investment Promotion Centre) accompagne les investisseurs.\n\n**Formes :** Limited Liability Company, Partnership, Sole Proprietorship\n**Délai :** 5-10 jours.",
                'taxation' => "**CIT :** 25%\n**VAT :** 15% (+ levies = ~21.9%)\n**Withholding Tax dividendes :** 8%\n**Free Zones :** 0% IS pour 10 ans, 15% ensuite.",
                'investment_incentives' => "- **GIPC Act** : seuils d'investissement minimaux mais avantages garantis\n- **Free Zones Scheme** : exonération totale 10 ans\n- **One District, One Factory (1D1F)** : soutien à l'industrialisation locale\n- **Ghana Beyond Aid** : stratégie de transformation économique\n- **AfCFTA** : siège du secrétariat à Accra",
                'risks' => "- Crise de la dette (restructuration FMI 2023)\n- Dépréciation du cedi\n- Déficit énergétique (Dumsor)\n- Dépendance aux matières premières (or, cacao, pétrole)",
                'opportunities' => "- Démocratie stable (alternances pacifiques)\n- Siège de l'AfCFTA (Zone de Libre-Échange Continentale)\n- Population jeune et éduquée\n- Écosystème tech en croissance (Accra Tech Hub)\n- Programme \"Year of Return\" pour la diaspora",
                'diaspora_programs' => "- **Diaspora Affairs Office** (Office of the President)\n- **Year of Return (2019) / Beyond the Return**\n- **Ghana Diaspora Homecoming Summit**\n- **Right of Abode** pour la diaspora africaine\n- **Diaspora Vote** (en discussion)",
                'investment_agency' => 'GIPC (Ghana Investment Promotion Centre)',
                'investment_agency_url' => 'https://www.gipcghana.com',
            ],
            [
                'country' => 'Tunisie',
                'country_code' => 'TN',
                'flag' => '🇹🇳',
                'currency' => 'TND',
                'official_language' => 'Arabe / Français',
                'population' => 12,
                'gdp' => 46.3,
                'gdp_growth' => 2.4,
                'remittances_gdp' => 5.1,
                'ease_of_business_score' => 68.7,
                'key_sectors' => ['Fintech', 'Healthtech', 'Industrie', 'Edtech'],
                'legal_framework' => "La Tunisie dispose du Startup Act le plus avancé d'Afrique (2018). Le code d'investissement (2016) garantit la liberté d'investissement. L'APII est le guichet unique.\n\n**Formes :** SARL, SA, SUARL\n**Délai :** 24-72h.",
                'taxation' => "**IS :** 15% (standard, réduit en 2021 depuis 25%)\n**TVA :** 19%\n**Retenue dividendes :** 10%\n**Startup Act :** exonération IS totale pendant 8 ans + congé de charges sociales.",
                'investment_incentives' => "- **Startup Act (2018)** : modèle pour l'Afrique — exonération totale 8 ans, bourse de 12 mois\n- **Zones de développement régional** : avantages renforcés\n- **Technopoles** : El Ghazala (IT), Borj Cedria (Biotech), Sfax (IT)\n- **Accord d'association UE** : accès au marché européen",
                'risks' => "- Instabilité politique post-2011\n- Chômage élevé (16%+)\n- Inflation croissante\n- Fragilité des finances publiques",
                'opportunities' => "- Capital humain très qualifié (ingénieurs, médecins)\n- Proximité géographique avec l'Europe\n- Startup Act le plus avancé du continent\n- Nearshoring IT en pleine expansion\n- Coûts compétitifs",
                'diaspora_programs' => "- **OTE (Office des Tunisiens à l'Étranger)** : accompagnement\n- **STEG Diaspora** : programmes énergie\n- **Concours national de la meilleure startup diaspora**\n- **Conventions fiscales** avec 55+ pays",
                'investment_agency' => 'APII (Agence de Promotion de l\'Industrie et de l\'Innovation)',
                'investment_agency_url' => 'https://www.tunisieindustrie.nat.tn',
            ],
            [
                'country' => 'Éthiopie',
                'country_code' => 'ET',
                'flag' => '🇪🇹',
                'currency' => 'ETB',
                'official_language' => 'Amharique',
                'population' => 126,
                'gdp' => 126.0,
                'gdp_growth' => 6.1,
                'remittances_gdp' => 0.7,
                'ease_of_business_score' => 48.0,
                'key_sectors' => ['Agritech', 'Industrie', 'Énergie', 'Commerce & Retail'],
                'legal_framework' => "L'Éthiopie a ouvert son économie aux investisseurs étrangers avec le nouveau code commercial (2021). L'Ethiopian Investment Commission (EIC) est le guichet unique. Certains secteurs restent protégés (banque, télécom — en cours d'ouverture).\n\n**Formes :** PLC (Private Limited Company), Share Company\n**Délai :** 1-3 jours via EIC.",
                'taxation' => "**Profit Tax :** 30%\n**TVA :** 15%\n**Withholding Tax dividendes :** 10%\n**Tax holiday :** 2-9 ans selon le secteur et la région.",
                'investment_incentives' => "- **Tax holidays** de 2 à 9 ans pour les secteurs prioritaires\n- **Industrial Parks** : Hawassa, Bole Lemi, Kilinto — clé en main\n- **Duty-free import** de machines et matières premières\n- **Export incentives** pour les entreprises orientées export",
                'risks' => "- Conflit au Tigré (réconciliation en cours)\n- Tensions ethniques régionales\n- Restrictions sur les devises étrangères\n- Bureaucratie lourde\n- Secteur télécom monopole d'État (ouverture Safaricom en cours)",
                'opportunities' => "- 2ème population d'Afrique (126M) = immense marché\n- Croissance rapide et soutenue\n- Grand barrage de la Renaissance (GERD) : énergie\n- Hub industriel émergent (textile, cuir, agro)\n- Addis-Abeba : siège de l'Union Africaine",
                'diaspora_programs' => "- **Diaspora Agency** (rattachée au PM)\n- **Diaspora Trust Fund** pour le GERD\n- **Origin ID Card** : carte d'identité diaspora (\"Yellow Card\")\n- **Exemptions douanières** pour le retour\n- **Diaspora Mortgage** via banques éthiopiennes",
                'investment_agency' => 'EIC (Ethiopian Investment Commission)',
                'investment_agency_url' => 'https://www.investethiopia.gov.et',
            ],
        ];

        foreach ($countries as $data) {
            CountryGuide::updateOrCreate(
                ['country_code' => $data['country_code']],
                $data
            );
        }
    }
}
